{
 "title": "Статистика со стороны Рекламодателя",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "advertiser",
    "label": "Рекламодатель",
    "query": {
     "query": "label_values(advertee_business_daily_count,advertiser)"
    }
   },
   {
    "name": "campaign",
    "label": "Кампания",
    "query": {
     "query": "label_values(advertee_business_daily_count{advertiser=~\"$advertiser\"},campaign)"
    }
   },
   {
    "name": "day",
    "label": "День (влияет только на row \"Суммарные данные\")",
    "query": {
     "query": "label_values(advertee_business_daily_count,day)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Статистика по дням", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Количество действий",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(advertee_business_daily_count{type=\"IMPRESSION\", campaign=~\"$campaign\"}) by (day, type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(advertee_business_daily_count{type=\"CLICK\", campaign=~\"$campaign\"}) by (day, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Конверсия (CTR)",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(advertee_business_daily_count{type=\"CLICK\", campaign=~\"$campaign\"}) by (day) / sum(advertee_business_daily_count{type=\"IMPRESSION\", campaign=~\"$campaign\"}) by (day)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Денег потрачено",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(advertee_business_daily_revenue{type=\"CLICK\", campaign=~\"$campaign\"}) by (day, type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(advertee_business_daily_revenue{type=\"IMPRESSION\", campaign=~\"$campaign\"}) by (day, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Суммарные данные",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Потрачено",
     "type": "stat",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(advertee_business_daily_revenue{day=~\"$day\", campaign=~\"$campaign\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Потрачено всего",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(advertee_business_daily_revenue{day=~\"$day\", campaign=~\"$campaign\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Конверсия (CTR)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(advertee_business_daily_count{campaign=~\"$campaign\", day=~\"$day\", type=\"CLICK\"}) / clamp_min(sum(advertee_business_daily_count{campaign=~\"$campaign\", day=~\"$day\", type=\"IMPRESSION\"}), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Количество действий",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(advertee_business_daily_count{campaign=~\"$campaign\", day=~\"$day\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}