{
 "title": "Статистика со стороны Бизнеса",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Прибыль",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(advertee_business_daily_revenue{type=\"CLICK\"}) by (day, type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(advertee_business_daily_revenue{type=\"IMPRESSION\"}) by (day, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество действий",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(advertee_business_daily_count{type=\"IMPRESSION\"}) by (day, type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(advertee_business_daily_count{type=\"CLICK\"}) by (day, type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Всего кампаний",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertee_business_campaigns_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Активных кампаний (сейчас)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertee_business_active_campaigns",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Запросов на ручную модерацию",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "advertee_review_requests_active",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}